name: create_PR

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: create pull request
        run: gh pr create --title "The bug is fixed" --body "Everything works again"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
