name: Automatically create pull request

on:
  push:
    branches:
      - db-failover*

jobs:
  open-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - run: |
          gh pr edit ${{ env.BRANCH_NAME }} -b '${{ env.PR_BODY }}' -t '${{ env.PR_TITLE }}' && gh pr reopen ${{ env.BRANCH_NAME }} || gh pr create -B main -t 'db failover' -r weishunliao -F "pull_request_template.md"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
