name: Open new PR
on: workflow_dispatch

jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh pr create --repo ${{ github.repository }} -B main -H db-failed-over --title 'Merge branch_to_merge into base_branch' --template "pull_request_template.md"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
