name: Automatically create pull request

on:
  push:
    branches:
      - db-failover

jobs:
  open-pr:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh pr create --repo ${{ github.repository }} -B main -t 'db failover' -b 'body'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
