name: Open new PR
on: workflow_dispatch

jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh pr create --repo ${{ github.repository }} -B main -H db-failed-over --title "db failover" --body "Detailed description of the changes"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
