name: Automatically create pull request

on:
  push:
    branches:
      - db-failover*

jobs:
  open-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          gh pr view $GITHUB_REF_NAME && gh pr reopen $GITHUB_REF_NAME || gh pr create -B main -H $GITHUB_REF_NAME -t 'Database failover' -r weishunliao -F pull_request_template.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
