name: Automatically create pull request

on:
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:

jobs:
  create_pr_repo_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "db failover"
          pr_template: "pull_request_template.md"
          pr_reviewer: "prov"
