name: Automatically create pull request

on:
  push:
    branches:
      - db-failover*

jobs:
  open-pr:
    runs-on: ubuntu-latest
    permissions:
      # actions: write
      # attestations: read|write|none
      checks: write
      contents: read
      # deployments: read|write|none
      # id-token: write|none
      # issues: read|write|none
      # discussions: read|write|none
      # packages: read|write|none
      # pages: read|write|none
      pull-requests: write
      # repository-projects: write
      # security-events: read|write|none
      # statuses: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          gh pr view ${{ env.BRANCH }} && gh pr reopen ${{ env.BRANCH }} || gh pr create -B main -H ${{ env.BRANCH }} -t 'Database failover' -r weishunliao -F pull_request_template.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.ref_name }}
