name: Open new PR
on: workflow_dispatch

jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh pr create --repo ${{ github.repository }} -B main -H db-failed-over --fill -F pull_request_template.md -t 'failover'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
