name: Automatically create pull request

on:
  push:
    branches:
      - db-failover*

jobs:
  open-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - run: |
          gh pr create -B main --title "Merge ${{ github.ref_name }} into develop" --body 'Created by Github action' || gh pr edit -B main --title "Merge ${{ github.ref_name }} into develop" --body 'Created by Github action'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
